blank_issues_enabled: false
contact_links:
  - name: Pi-hole Community Support
    url: https://discourse.pi-hole.net/
    about: Get help with Pi-hole configuration
  - name: Documentation
    url: https://docs.pi-hole.net/
    about: Check the Pi-hole documentation
  - name: Blocklist Format Guide
    url: https://github.com/mrxehmad/pi-hole-adlist/wiki/Format-For-Pi%E2%80%90hole-Adlist-Collection
    about: Learn how to format blocklist entries
